# Generated by Django 5.1.4 on 2025-01-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
