# Generated by Django 5.1.4 on 2025-02-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_userprofile_image_userprofile_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Image',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile',
            field=models.ImageField(null=True, upload_to='items/'),
        ),
    ]
