# Generated by Django 5.1.4 on 2025-02-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_rename_image_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default='images.jpg', null=True, upload_to='posts/images/'),
        ),
    ]
