# Generated by Django 5.1.4 on 2025-02-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
