# Generated by Django 5.1.4 on 2025-03-10 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0018_chatmessage_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='file',
            new_name='photo',
        ),
    ]
