# Generated by Django 5.1.4 on 2025-03-11 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0019_rename_file_chatmessage_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
