# Generated by Django 5.1.4 on 2025-03-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0020_post_is_banned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, default='Country', max_length=55, null=True),
        ),
    ]
